### ISSUE TITLE
Add parenthises automatically

### ISSUE THREAD

**Issue by gampleman** [the-sett/elm-syntax-dsl#44]
```elm
import Elm.CodeGen as CodeGen
import Elm.Pretty
import Pretty

expr =
    CodeGen.apply
        [ CodeGen.val "map"
        , CodeGen.construct "C" []
        , CodeGen.apply [ CodeGen.val "foo", CodeGen.val "arg" ]
        ]


result =
    Elm.Pretty.prettyExpression expr |> Pretty.pretty 120
```

unexpectedly prints `map C foo arg`.

That's clearly not the correct interpretation of the AST. You could claim that the AST is incorrect as it should have a `CodeGen.parens` wrapping the `CodeGen.apply`, but this makes using CodeGen not easily composable. 

Consider that you want to apply a function to another `Expression`. Now you have work out whether or not the parentheses are necessary, usually by peaking inside the returned expression, even though it should be fairly clear from the AST where the parentheses are necessary.

Related issue https://github.com/the-sett/elm-syntax-dsl/issues/9.

Happy to take a stab at implementing this, if you consider this reasonable.

**Comment by rupertlssmith** [comment]
There is probably enough context on the elm-syntax Expression to figure out whether or not an argument is not a simple atom:

https://package.elm-lang.org/packages/stil4m/elm-syntax/latest/Elm-Syntax-Expression#Expression

Also, ParenthesizedExpression already has parenthesis on it, so that one you would skip adding them.
